fixed commented problems
Shakhzod-Elturaev/film-loader-service pull request #1
Opened 2023-10-20 09:42 UTC by Shakhzod-Elturaev

2023-10-20 10:31 UTC, Shakhzod-Elturaev commented on src/main/java/com/vention/filmloaderservice/domain/entity/MovieEntity.java
> +public class MovieEntity {
I merged RatingEntity fields with MovieEntity because it causes a complexity for database and database normalization

2023-10-20 10:33 UTC, Shakhzod-Elturaev commented on src/main/java/com/vention/filmloaderservice/listener/LoaderServiceListener.java
> +    public void contextInitialized(ServletContextEvent sce) {
I created separate methods for movie service injection and for injecting movie service to controllers. That one was mentioned by Vadzim

2023-10-20 10:35 UTC, Shakhzod-Elturaev commented on src/main/java/com/vention/filmloaderservice/repository/genre/GenreRepositoryImpl.java
> +            if(!Arrays.stream(batchResults).allMatch(result -> result >= 0)) {
I also checked batch processing here. If any of this return negative number, transaction fails

2023-10-20 10:38 UTC, Shakhzod-Elturaev commented on src/main/java/com/vention/filmloaderservice/service/genre/GenreServiceImpl.java
> +        for (String genreName : stringSet) {
why I use Set<String> because I can send list of movies and they may have the same genre, so first I just got all genre names into this set ( set does not contain any duplicates), and created new GenreEntity and save them all into database

2023-10-20 10:40 UTC, Shakhzod-Elturaev commented on src/main/java/com/vention/filmloaderservice/service/movie/MovieServiceImpl.java
> +
I tried to use transaction manually, but I am not 100 % sure that it is correctly organized, so if any mistakes, I would appreciate your feedbacks for that

2023-10-20 10:41 UTC, Shakhzod-Elturaev commented on src/main/java/com/vention/filmloaderservice/service/moviegenre/MovieGenreServiceImpl.java
> +
This class is used to do operations related to movie and genre relationship

2023-10-20 10:42 UTC, Shakhzod-Elturaev commented on src/main/java/com/vention/filmloaderservice/utils/Utils.java
> +        return new ObjectMapper()
I added the method to get ObjectMapper instance. It was mentioned by Vadzim

2023-10-20 10:48 UTC, Shakhzod-Elturaev commented on src/main/java/com/vention/filmloaderservice/repository/movie/MovieRepositoryImpl.java
> +            connection.setAutoCommit(false);
that connection.setAutoCommit(false) is mistake, I just forgot to delete it and I will fix it alongside todays comments

2023-10-20 10:49 UTC, Shakhzod-Elturaev commented on src/main/java/com/vention/filmloaderservice/repository/movie/MovieRepositoryImpl.java
> +            connection.setAutoCommit(false);
also that one

2023-10-20 11:21 UTC, AlRezz commented on src/main/java/com/vention/filmloaderservice/repository/genre/GenreRepositoryImpl.java
> +            if(!Arrays.stream(batchResults).allMatch(result -> result >= 0)) {
Stream contains nonMatch()

2023-10-20 11:25 UTC, AlRezz commented on src/main/java/com/vention/filmloaderservice/utils/Utils.java
> +        return new ObjectMapper()
Looks like you'll return a new instance of ObjectMapper each time when you will call getObjectMapper(). And if you've got a specific setting for the Object Mapper, they will be lost.
You need to init an ObjectMapper as the Util.class variable and return it.

2023-10-20 11:32 UTC, AlRezz commented on src/main/java/com/vention/filmloaderservice/service/movie/MovieServiceImpl.java
> +                    } catch (SQLException ex) {
we were talking about verbose logs. cover it throw the all project

2023-10-20 11:33 UTC, AlRezz requested changes
Check comments.
Add readable logs

2023-10-23 07:11 UTC, AlRezz commented on src/main/java/com/vention/filmloaderservice/controller/MovieRetrievalController.java
> +        MovieDto save = movieService.save(movieId);
What's happen if movieId = null?

2023-10-23 07:11 UTC, AlRezz commented on src/main/java/com/vention/filmloaderservice/controller/TopMoviesRetrievalController.java
> +        String page = request.getParameter("page");
what's happen if page=null?

2023-10-23 07:14 UTC, AlRezz commented on src/main/java/com/vention/filmloaderservice/service/movie/MovieServiceImpl.java
> +                    }
still have printStackTrace

2023-10-23 07:27 UTC, AlRezz requested changes
Can not see controllers to retrieve top250 and film by id. 
Points 1 and 2 says 
Ability to load TOP-250 by schedule and on demand (api/v2.2/films/top?type=TOP_250_BEST_FILMS)
Ability to load information about movies and save to the DB any film manually (/api/v2.2/films/{id}). 
So, you have to be able to call top250 endpoint manually.
More over point 6 says
Only the Administrator has access to the TOP_250 and getFilmById and endpoints. In this case we need to implement a security filter.
In this case you need to implement security filter and check these endpoints. As far as we do need real security in this service, you can add a specific header to the request and check it.
 Your MovieService interface should contain loadTop250 and LoadFilmById methods.
And the most important thing - MovieServiceImpl  and LocalStorageMovieService  have to implement the same interface 'cause we do need to know where data come from.

2023-10-26 12:32 UTC, merged